# baseurl is the location of the generated site from the browser's
# perspective (e.g., http://doc.arvados.org or
# file:///tmp/arvados/doc/.site). To make docs show up inside
# workbench, use /doc here and add a symlink at
# apps/workbench/public/doc pointing to ../../../doc/.site

baseurl: /doc

exclude: ["Rakefile", "tmp", "vendor"]
arvados_api_host: qr1hi.arvadosapi.com

navbar:
  userguide:
    - Getting Started:
      - user/index.html.textile.liquid
      - user/getting_started/workbench.html.textile.liquid
      - user/getting_started/ssh-access.html.textile.liquid
      - user/getting_started/check-environment.html.textile.liquid
      - user/getting_started/community.html.textile.liquid
    - Tutorials:
      - user/tutorials/tutorial-keep.html.textile.liquid
      - user/tutorials/tutorial-job1.html.textile.liquid
      - user/tutorials/tutorial-firstscript.html.textile.liquid
      - user/tutorials/tutorial-job-debug.html.textile.liquid
      - user/tutorials/tutorial-parallel.html.textile.liquid
      - user/tutorials/tutorial-new-pipeline.html.textile.liquid
      - user/tutorials/tutorial-trait-search.html.textile.liquid
      - user/tutorials/tutorial-gatk-variantfiltration.html.textile.liquid
      - user/tutorials/running-external-program.html.textile.liquid
    - Examples:
      - user/examples/crunch-examples.html.textile.liquid
    - Reference:
      - user/reference/api-tokens.html.textile.liquid
      - user/reference/sdk-cli.html.textile.liquid
  sdk:
    - Overview:
      - sdk/index.html.textile.liquid
    - Python:
      - sdk/python/sdk-python.html.textile.liquid
      - sdk/python/python.html.textile.liquid
      - sdk/python/crunch-utility-libraries.html.textile.liquid
  api:
    - Concepts:
      - api/index.html.textile.liquid
      - api/authentication.html.textile.liquid
      - api/methods.html.textile.liquid
      - api/resources.html.textile.liquid
      - api/crunch-scripts.html.textile.liquid
      - api/permission-model.html.textile.liquid
    - API Methods:
      - api/methods/api_client_authorizations.html.textile.liquid
      - api/methods/api_clients.html.textile.liquid
      - api/methods/authorized_keys.html.textile.liquid
      - api/methods/collections.html.textile.liquid
      - api/methods/groups.html.textile.liquid
      - api/methods/humans.html.textile.liquid
      - api/methods/jobs.html.textile.liquid
      - api/methods/job_tasks.html.textile.liquid
      - api/methods/keep_disks.html.textile.liquid
      - api/methods/links.html.textile.liquid
      - api/methods/logs.html.textile.liquid
      - api/methods/nodes.html.textile.liquid
      - api/methods/pipeline_instances.html.textile.liquid
      - api/methods/pipeline_templates.html.textile.liquid
      - api/methods/repositories.html.textile.liquid
      - api/methods/specimens.html.textile.liquid
      - api/methods/traits.html.textile.liquid
      - api/methods/users.html.textile.liquid
      - api/methods/virtual_machines.html.textile.liquid
    - Schema:
      - api/schema/ApiClientAuthorization.html.textile.liquid
      - api/schema/ApiClient.html.textile.liquid
      - api/schema/AuthorizedKey.html.textile.liquid
      - api/schema/Collection.html.textile.liquid
      - api/schema/CommitAncestor.html.textile.liquid
      - api/schema/Commit.html.textile.liquid
      - api/schema/Group.html.textile.liquid
      - api/schema/Human.html.textile.liquid
      - api/schema/Job.html.textile.liquid
      - api/schema/JobTask.html.textile.liquid
      - api/schema/KeepDisk.html.textile.liquid
      - api/schema/Link.html.textile.liquid
      - api/schema/Log.html.textile.liquid
      - api/schema/Node.html.textile.liquid
      - api/schema/PipelineInstance.html.textile.liquid
      - api/schema/PipelineTemplate.html.textile.liquid
      - api/schema/Repository.html.textile.liquid
      - api/schema/Specimen.html.textile.liquid
      - api/schema/Trait.html.textile.liquid
      - api/schema/User.html.textile.liquid
      - api/schema/VirtualMachine.html.textile.liquid
  admin:
    - Admin:
      - admin/index.html.md.liquid
      - admin/cheat_sheet.html.textile.liquid
  installguide:
    - Install:
      - install/install-api-server.html.md.liquid
      - install/index.html.md.liquid
      - install/install-workbench-app.html.md.liquid
      - install/client.html.textile.liquid
      - install/create-standard-objects.html.textile.liquid
      - install/install-crunch-dispatch.html.textile.liquid
